Add dynamic data
kentomeister/projCatWalk pull request #14
Opened 2021-04-21 14:14 UTC by gharti2704

2021-04-21 18:51 UTC, alexzinnde requested changes

2021-04-21 18:51 UTC, alexzinnde commented on .gitignore
> -node_modules
We want to git to ignore the node_modules folder. Please add  nod_moduels to the .git_ignore

2021-04-21 18:51 UTC, alexzinnde commented on server/app.js
> +app.get('/:id', (req, res) => {
I suggest you change your endpoint to be more specific to your widget. I suggest something like: 
`app.get('/relatedProducts/:id'`...

2021-04-21 18:51 UTC, alexzinnde commented on server/app.js
> +  api.getRelatedProductId(id, (err, response) => {
If you can, I suggest refactoring your callback to a promise pattern, so our code has more uniformity.

2021-04-21 18:51 UTC, alexzinnde commented on src/components/related-items-comparison/ProductInformation.jsx
> +  console.log(product, 'Hi! You clicked me!!!!');
let's remove console.logs unless absolutely necessary

2021-04-21 18:51 UTC, alexzinnde commented on src/components/related-items-comparison/RelatedProductCard.jsx
> +// require('dotenv').config();
You don't need to require dotenv inside your component. Only need this inside the server to hold the github token info

2021-04-21 18:51 UTC, alexzinnde commented on src/components/related-items-comparison/RelatedProductCard.jsx
> +  //const [product, setProduct] = useState([]);
I don't think you can use useState inside a class component.

2021-04-22 18:05 UTC, gharti2704 commented on src/components/related-items-comparison/RelatedProductCard.jsx
> +  //const [product, setProduct] = useState([]);
Error fixed.

2021-04-22 19:43 UTC, alexzinnde approved these changes

2021-04-22 19:43 UTC, alexzinnde commented on src/components/related-items-comparison/Outfit.jsx
> +  console.log(products);
Remove the console.log here.

2021-04-22 19:43 UTC, alexzinnde commented on src/components/related-items-comparison/RelatedProductCard.jsx
> +    console.log(id);
Remove the console.log here

2021-04-22 19:44 UTC, merged